<?php

$cp = [
            "58000",
            "58004",
            "58006",
            "58009",
            "58010",
            "58013",
            "58020",
            "58030",
            "58040",
            "58048",
            "58049",
            "58050",
            "58055",
            "58056",
            "58057",
            "58058",
            "58060",
            "58066",
            "58067",
            "58069",
            "58070",
            "58078",
            "58080",
            "58085",
            "58086",
            "58087",
            "58088",
            "58089",
            "58090",
            "58093",
            "58095",
            "58096",
            "58097",
            "58098",
            "58099",
            "58100",
            "58110",
            "58114",
            "58115",
            "58116",
            "58117",
            "58118",
            "58120",
            "58127",
            "58128",
            "58130",
            "58140",
            "58145",
            "58146",
            "58147",
            "58148",
            "58149",
            "58150",
            "58158",
            "58160",
            "58168",
            "58170",
            "58175",
            "58178",
            "58179",
            "58180",
            "58183",
            "58186",
            "58187",
            "58188",
            "58189",
            "58190",
            "58194",
            "58195",
            "58196",
            "58197",
            "58199",
            "58200",
            "58210",
            "58216",
            "58217",
            "58218",
            "58219",
            "58220",
            "58226",
            "58227",
            "58228",
            "58229",
            "58230",
            "58240",
            "58244",
            "58245",
            "58248",
            "58249",
            "58250",
            "58253",
            "58254",
            "58255",
            "58256",
            "58257",
            "58258",
            "58259",
            "58260",
            "58270",
            "58277",
            "58278",
            "58280",
            "58290",
            "58295",
            "58296",
            "58297",
            "58300",
            "58301",
            "58302",
            "58303",
            "58304",
            "58310",
            "58312",
            "58313",
            "58317",
            "58320",
            "58321",
            "58322",
            "58323",
            "58324",
            "58330",
            "58331",
            "58332",
            "58333",
            "58334",
            "58335",
            "58336",
            "58337",
            "58338",
            "58340",
            "58341",
            "58342",
            "58343",
            "58344",
            "58345",
            "58346",
            "58347",
            "58348",
            "58350",
            "58352",
            "58353",
            "58355",
            "58356",
            "58357",
            "58358",
            "58359" 
        ];

        $colonia = [
            "INFONAVIT El Pipila",
            "Universidad Michoacana de San Nicolas de Hidalgo",
            "Secretaria de Salud",
            "Palacio de Gobierno Del Estado de Michoacan",
            "Juarez",
            "Supremo Tribunal de Justicia",
            "Cuauhtemoc",
            "Morelos",
            "Felicitas del Rio",
            "FOVISSSTE La Huerta",
            "Jardines del Toreo",
            "Hacienda Penasco",
            "Villas de Fatima",
            "Arboledas",
            "Los Pinos de Michoacan",
            "Morelia 450",
            "Alberto Oviedo Mota",
            "Valle Quieto",
            "INFONAVIT Benito Juarez",
            "INFONAVIT Villa Universidad",
            "Felix Ireta",
            "Condominio Planetario",
            "Colonial Morelia",
            "Balcones de Morelia",
            "Hermanos Lopez Rayon",
            "El Cerrito",
            "Andres Quintana Roo",
            "Ampliacion Nor-oeste La Huerta",
            "Balcones de Santa Maria",
            "Torres Panorama",
            "Villas del Sur II",
            "Lomas del Durazno",
            "Carlos Rivas Larrauri",
            "Lomas de Vista Bella",
            "Nueva Jacarandas",
            "Los Angeles",
            "Ejidal Francisco Villa",
            "La Joya",
            "Lago I",
            "Ampliacion El Realito",
            "Lomas del Tecnologico",
            "Barrio Alto",
            "Enrique Arreguin Velez",
            "Felipe Carrillo Puerto",
            "Alfonso Garcia Robles",
            "Industrial",
            "Cuatro de Marzo",
            "Centro SCT Michoacan",
            "Francisca Xaviera Villegas",
            "Defensores de Puebla",
            "Emiliano Zapata",
            "Vistas del Quinceo",
            "Bocanegra",
            "Carlos Salazar",
            "El Porvenir",
            "Ampliacion El Porvenir",
            "Lomas del Valle",
            "Ejidal Tres Puentes",
            "Las Mariposas",
            "Heroes de Bajan",
            "Adolfo Lopez Mateos",
            "Paseo del Alamo",
            "Campestre los Manantiales",
            "INFONAVIT Juan Aldama",
            "Manantiales Poniente",
            "Agua Clara",
            "Agustin Arriaga Rivera",
            "Praderas de Morelia",
            "Los Ciruelos",
            "INDECO El Vivero",
            "Villas Morelianas",
            "INFONAVIT CEPAMISA",
            "Ciudad Industrial",
            "Articulo 27 Constitucional",
            "Bosques de Oriente",
            "Primo Tapia",
            "Ampliacion Division del Norte",
            "Congreso Constituyente de Michoacan",
            "Enrique Ramirez",
            "Union",
            "Vicente Lombardo Toledano",
            "Buenavista I",
            "Lazaro Cardenas",
            "Cinco de Mayo",
            "Erendira",
            "INFONAVIT Lomas de Hidalgo",
            "Virreyes",
            "Hospitales de Don Vasco",
            "El Mirador del Punhuato",
            "Insurgentes",
            "Los Abedules",
            "Puerta Tres Marias Norte",
            "Eucaliptos",
            "Lomas del Punhuato",
            "Paseo de las Lomas",
            "Paraiso Monarca",
            "FOVISSSTE Acueducto",
            "Punta Terraverde",
            "Jardines del Rincon",
            "Del Periodista",
            "Cumbres Morelia",
            "Cinco de Diciembre",
            "Bosque Camelinas",
            "Ejidal Ocolusen",
            "Club Campestre de Morelia",
            "Cundagua",
            "Atapaneo",
            "Rio Bello ",
            "Puerto de Buenavista",
            "Francisco J. Mugica",
            "Mision del Valle",
            "Cotzurio",
            "Asiento de Piedra ",
            "El Pino ",
            "El Porvenir ",
            "Teremendo de los Reyes",
            "Coro Grande",
            "Tzintzimacato Chico",
            "Aracurio",
            "Teremendo Jasso",
            "Jardin de la Montana",
            "Buenavista",
            "Cuanajillo Grande",
            "Iratzio",
            "El Correo",
            "Joyitas",
            "San Jose Itzicuaro ",
            "Ampliacion San Pascual",
            "Las Flores",
            "San Nicolas Obispo",
            "Bosques de la Presa",
            "San Javier Xanamurhu",
            "Santa Rosalia",
            "El Banito",
            "El Aguaje",
            "El Escobal",
            "Chihuerio",
            "Cointzio",
            "Lartesi",
            "Puente Hernandez",
            "Loma Caliente",
            "Las Mesitas",
            "Puentecillas ",
            "Tumbisca",
            "Torrecillas ",
            "El Durazno",
        ];
        
?>