<?php

$cp = [
            '58194',
            '58149',
            '58195',
            '58130',
            '58150',
            '58090',
            '58260',
            '58060',
            '58087',
            '58160',
            '58020',
            '58230',
            '58270',
            '58280',
            '58188',
            '58290',
            '58197',
            '58140',
            '58057',
            '58240',
            '58049',
            '58336',
            '58050',
            '58337',
            '58110',
            '58178',
            '58080',
            '58200',
            '58210',
            '58277',
            '58069',
            '58066',
            '58096',
            '58040',
            '58217',
            '58146',
            '58100',
            '58116',
            '58026',
            '58089',
            '58099',
            '58118',
            '58115',
            '58088',
            '58229',
            '58401',
            '58226',
            '58254',
            '58128',
            '58295',
            '58228',
            '58147',
            '58219',
            '58180',
            '91234',
            '58114',
            '58148',
            '58218',
            '58330',
            '58257',
            '58258',
            '58348',
            '50180',
            '58142',
            '58510',
            '58095',
            '50800',
            '58220',
            '58030',
            '58880',
            '58249',
            '58158',
            '58255',
            '58179',
            '58127',
            '58248',
            '58175',
            '58341',
            '48295',
            '57115',
            '58250',
            '58168',
            '57089',
            '50140',
            '58011',
            '58028',
            '58580',
            '50810',
            '5801',
            '58244',
            '58256',
            '58187',
            '58117',
            '5825',
            '20289',
            '50170',
            '58300',
            '28090',
            '52250',
            '58186',
            '55809',
            '58121',
            '58241',
            '58196',
            '58111',
            '58410',
            '38040',
            '28210',
            '58832',
            '58113',
            '6600',
            '12349',
            '5800',
            '58135',
            '58223',
            '58165',
            '58800',
            '51210',
            '58075',
            '50188',
            '58189',
            '56200',
            '64000',
            '58068',
            '58123',
            '58143',
            '85116',
            '58157',
            '55115',
            '64480',
            '1210',
            '98218',
            '50000',
            '58384',
            '58279',
            '58297',
            '58091',
            '58174',
            '56115',
            '58343',
            '58144',
            '53230',
            '58233',
            '43541',
            '58154',
            '53337',
            '58062',
            '58058',
            '58185',
            '58216',
            '52230',
            '14020',
            '50130',
            '50090',
            '28260',
            '58314',
            '38116',
            '53887',
            '58098',
            '52140',
            '51116',
            '58039',
            '58184',
            '38090',
            '58770',
            '53929',
            '56290',
            '38980',
            '58025',
            '47400',
            '58235',
            '58264',
            '15814',
            '58085',
            '58038',
            '58740',
            '68114',
            '58056',
            '58067',
            '58003',
            '58079',
            '38983',
            '50240',
            '58262',
            '52270',
            '60156',
            '58296',
            '58888',
            '58891',
            '58141',
            '38280',
            '48050',
            '58344',
            '55200',
            '58537',
            '58259',
            '58331',
            '58313',
            '53331'

    
];

$colonia = [
            'CAMPESTRE DEL VERGEL',
            'FRACCIONAMIENTO NICOLAITAS ILUSTRES',
            'LA CALERA',
            'COLONIA OBRERA',
            'FRACCIONAMIENTO TRES PUENTES',
            'SANTA MARIA DE GUIDO',
            'COLONIA CHAPULTEPEC NORTE',
            'VILLA UNIVERSIDAD',
            'COLONIA VIVEROS',
            'LAS FLORES',
            'COLONIA VENTURA PUENTE',
            'COLONIA VASCO DE QUIROGA',
            'FRACCIONAMIENTO LAS AMERICAS',
            'NUEVA CHAPULTEPEC SUR',
            'COLONIA LOS MANANTIALES',
            'COLONIA BOSQUE CAMELINAS',
            'FRACCIONAMIENTO TORREMOLINOS',
            'GUADALUPE',
            'FRACCIONAMIENTO LOS PINOS',
            'LOMAS DE HIDALGO',
            'FRACCIONAMIENTO JARDINES DEL TOREO',
            'FRACC. MANUEL VILLALONGIN',
            'MARIANO JIMENEZ',
            'COLONIA ARBOLEDAS VALLADOLID',
            'PRADOS VERDES',
            'LIBERTAD',
            'FRACCIONAMIENTO LA HUERTA',
            'CIUDAD INDUSTRIAL AMPLIACION SUR',
            'PRIMO TAPIA',
            'FRAY ANTONIO DE SAN MIGUEL',
            'FRACCIONAMIENTO VALLE QUIETO',
            'COLONIA VALLE QUIETO',
            'TRINCHERA DE MORELOS',
            'COLONIA FELICITAS DEL RIO',
            'EJIDAL ISAAC ARRIAGA',
            'LA QUEMADA',
            'FRACC. LOS ANGELES',
            'AMPLIACION TORREON NUEVO',
            'COLONIA VENTURA PUENTE',
            'FRACC-XAMGARI',
            'NUEVA JACARANDAS',
            'COLONIA LA SOLEDAD',
            'LAGO 1',
            'COLONIA FUENTES DE MORELIA',
            'COLONIA LAZARO CARDENAS',
            'COLONIA FELIX IRETA',
            'COLONIA IZAC ARRIAGA 2',
            'COLONIA FRAY ANTONIO DE LISBOA',
            'COLONIA JESUS ROMERO FLORES',
            'COLONIA EJIDAL OCOLUSEN',
            'BUENA VISTA',
            'FRACCIONAMIENTO NICOLAITAS ILUSTRES',
            'COLONIA CONGRESO CONSTITUYENTE DE MICHOACAN',
            'ADOLFO LOPEZ MATEOS',
            'SIN NOMBRE',
            'FRACCIONAMIENTO JARDINES DEL QUINCEI',
            'COLONIA JARDINES DE GUADALUPE',
            'COLONIA ELIAS PEREZ AVALOZ',
            'FRACCIONAMIENTO EL MIRADOR DEL QUINCEO',
            'PASEO DE LAS LOMAS',
            '18 DE MAYO',
            'COLONIA GRANJAS UNIDAS',
            'COLONIA ADOLFO LOPEZ MATEOS',
            'COLONIA EDUARDO RUIZ',
            'COLONIA GRANGAS DEL MAESTRO',
            'COLONIA COLINAS DEL SUR',
            'AV.FUENTES DE MORELIA',
            'VENTURA PUENTE',
            'MORELOS',
            'LUIS CORDOBA REYES LOMA COLORADA',
            'MIRADOR DEL PUNHUATO',
            'COLONIA CARLOS SALAZAR',
            'HOSPITALES DE DON VASCO',
            'JAUJILLA',
            'FELIPE CARRILLO PUERTO',
            'COLONIA UNIDOS SANTA CRUZ',
            'EJIDAL 3 PUENTES',
            'ZIMPANIO NORTE',
            'COLONIA EJIDAL OCOLUSEN',
            'COLONIA SOLIDARIDAD',
            'COLONIA PASCUAL ARTIZ DE AYALA',
            'EL PORVENIR',
            'XANGARI',
            'JAVIER MINA',
            'COLONIA NINOS HEROES',
            'BUENA VISTA',
            'COLONIA GRANJAS DEL MAESTRO',
            'JUAREZ',
            'MOLINO DE PARRAS',
            'INFONAVIT LOMAS DE HIDALGO',
            'LOMAS DE PUNGUATO',
            'COLONIA VISTA HERMOSA',
            'COLONIA LOMAS DEL TECNOLOGICO',
            'ZONA CENTRO',
            'PRIMO TAPIA ORIENTE',
            'INFONAVIT LA QUEMADA',
            'COLONIA SATELITE',
            'VISTA BELLA',
            'COLONIA PASCUAL ORTIZ AYALA',
            'CAMPESTRE LOS MANANTIALES',
            'COLINAS DEL SUR',
            'COLONIA FELIPE CARRILLO PUERTO',
            'BUENA VISTA',
            'SIN NOMBRE',
            'COLONIA JARDINES DE SANTIAGUITO',
            'WENCESLAO VICTORIA SOTO',
            'FELISITAS DEL RIO',
            'NUEVA UNION',
            'SAN RAFAEL',
            'FRACCIONAMIENTO IGNACIO RAMIREZ',
            'AMPLIACION LA SOLEDAD',
            'SIN NOMBRE',
            'ZONA CENTRO',
            'AGRICOLA DEL SUR',
            'ENRIQUE RAMIREZ',
            'LA CALERA',
            'FUENTES DE MORELIA',
            'ISAAC ARRIAGA',
            'NUEVA JACARANDAS',
            'COLONIA LA SOLEDAD',
            'VICENTE GUERRERO',
            'COLONIA CD INDUSTRIAL',
            'CIUDAD INDUSTRIAL MORELIA',
            'COLONIA LOMAS',
            'COLONIA AMPLIACION GERTRUDIS SANCHEZ',
            'MIRADOR DEL PONIENTE',
            'TORREON NUEVO',
            'COLONIA PRIMO TAPIA PONIENTE',
            'COLONIA AMPLIACION GERTRUDIS SANCHEZ',
            'COLONIA LOMAS DEL TECNOLOGICO',
            'IRRIGACION',
            'ELIAS PEREZ AVALOS',
            'COLONIA CENTRO',
            'COLONIA EL REALITO',
            'COL. OCOLUSEN',
            'EL REALITO',
            'CAMELINA',
            'FRACCIONAMIENTO LEANDRO VALLE',
            'COLONIA AMPLIACION EL REALITO',
            'COL. ELIAS PEREZ AVALOS',
            'COLONIA GUADALUPE',
            'COLONIA VASCO DE QUIROGA MORELIA MI',
            'PRIMERA ETAPA DE LACIUDAD INDU',
            'PASEO DE LAS LOMAS',
            'AMPLIACION',
            'MARIANO ABASOLO',
            'AMPLIACION VALLE QUIETO',
            'FRACCIONAMIENTO MORELIA 450',
            'FUENTES DE VALLADOLID',
            'FRACCIONAMIENTO BOSQUES DE ORIENTE',
            'EJIDAL ISACC ARRIAGA',
            'COLONIA SINDURO',
            'FRACCIONAMIENTO LAS ARBOLEDAS',
            'TLALPUJAHUA',
            'CHAPULTEPEC SUR',
            'ZIMPANIO NORTE',
            'FRACCIONAMIENTO VILLAS DEL REAL',
            'FRACC. SAN ISIDRO ITZUCUARO',
            'AMPLIACION LOMAS DE VISTA BELLA',
            'AMPLIACION DOCTOR FELIX ARREGUIN',
            'COLONIA VICENTE RIVA PALACIO',
            'COLONIA VICENTE RIVA PALACIO',
            'COLONIA UNIDOS SANTA CRUZ',
            'SANTA MARIA DE GUIDO',
            'LAS AMERICAS',
            'EX HDA LA HUERTA',
            'COLONIA JARDINES DEL RINCON',
            'CENTRO',
            'EL PORVENIR',
            'CENTRO',
            'COL. PASEO DE LAS LOMAS',
            'COLONIA CHAPULTEPEC NORTE',
            'COLONIA EDUARDO RUIZ',
            'COLONIA HERMANOS LOPEZ RAYON',
            'COLONIA MORELOS',
            'COLONIA GUADALUPE',
            'COLONIA PRADOS VERDES',
            'FRACCIONAMIENTO VISTA HERMOSA 2DA ETAPA',
            'COLONIA JARDINES DE MORELIA',
            'COLONIA RECTOR DIAZ RUBIO',
            'VENTURA PUENTE',
            'COLONIA PROGRESO',
            'COLONIA REY CHIMALPOPOCA',
            'CIUDAD INDUSTRIAL',
            'JARDINES DEL RINCON',
            'LA ESTRELLA',
            'LA LOMA DE LA CAMELINA',
            'LOMA COLORADA',
            'MORELIA',
            'COLONIA AMPLIACION FELIX ARREGUI',
            'FRACCIONAMIENTO PERIODISTAS',
            'AMPLIACION JARDINES DEL TOREO',
            'FRACCIONAMIENTO LAZARO CARDEN',
            'COLONIA SIN NOMBRE',
            'IGNACIO LOPEZ RAYON',
            'COLONIA LOMAS DE GUAYANGAREO',
            'BARRIO DE SAN FRANCISCO',
            'SIN NOMBRE',
            'COLONIA SIN MOMBRE'

];

$calles = [
        'ANTIGUO CAMINO LA HUERTA',
        'PADRE DE LA PATRIA',
        'ARAGON',
        'GUSTAVO A. MADERO',
        'MICHOACAN',
        'RAMON LOPEZ VELARDE',
        'ACUEDUCTO',
        'HOLANDA',
        'IGNACIO ALDAMA',
        'GARDENIA',
        'RIO AMATLAN',
        'ACUEDUCTO',
        'PERIFERICO NUEVA ESPANA',
        'GARCIA DE LEON',
        'MANANTIAL LOS AZUFRES',
        'TEHPACUA',
        'MARIANO TERCERO',
        'TLATELOLCO',
        'UNIVERSIDAD',
        'PROFESORA MARIA CONCEPCION SOLIS',
        'GANADERIA DEL ROCIO',
        'MANUEL VILLALONGIN',
        'BATALLA DE LAS CRUCES',
        'ANTONIO BELAN',
        'PASEO DEL OYAMEL',
        'GRITO DE INDEPENDENCIA',
        'MELON',
        'FRANCISCO I. MADERO ORIENTE',
        'FRANCISCO I. MADERO ORIENTE',
        'OBISPO DEL ACUEDUCTO',
        'VALLE DE ZAMORA',
        'VALLE DE GUAYANGAREO',
        'TRATADO DE ACAPULCO',
        'PROFESOR JOSE ROMERO FLORES',
        'FRANCISCO I. MADERO ORIENTE',
        'FRANCISCO I. MADERO PONIENTE',
        'CEDRO',
        'SALTA PARED',
        'LAGO DE CAMECUARO',
        'PIRERI',
        'TABACHIN',
        'MORELOS NORTE',
        'PERIFERICO REPUBLICA',
        'FUENTE DEL GALLO',
        'FRAY FRANCISCO JAVIER ALEGRE',
        'PERIFERICO NUEVA ESPANA',
        'LORENZO BOTURINI',
        'HERNANDO GUTIERREZ BOCANEGRA',
        'EL ZAPATISTA',
        'FRAY JUAN BAUTISTA LAGUNAS',
        'FRAY. SEBASTIAN DE APARICIO',
        'PERIFERICO REPUBLICA',
        'TIMOTEO GUERRERO',
        'DEL SOL',
        'PERIODISMO / JOSE TOCAVEN LAVIN',
        'GENERAL JOSE MARIA ROJO',
        'CAPITAN CARLOS ROVIROSA',
        'TENIENTE CORONEL FELIPE PARAMO',
        '23 DE OCTUBRE DE 1904',
        'HOMERO',
        'MIGUEL DE RIVERA',
        'FRANCISCO I. MADERO PONIENTE',
        'PRESIDENTE ADOLFO LOPEZ MATEOS',
        'BOCAMELIA',
        'GUILLERMO PRIETO',
        'LA JOYA / JOSE TRINIDAD GUIDO',
        'FUENTES DE MORELIA',
        'GARCIA OBESO',
        'LA PAZ',
        'LOMA BOLIVIANA',
        'JOAQUIN M. DEL CASTILLO',
        'CADETE SALAZAR',
        'HOSPITAL DE CHARO',
        'MARIANO SANCHEZ ARRIOLA',
        'BENEMERITO DE YUCATAN',
        'RIO CUPATITZIO',
        'JOSE MARIA IZAZAGA',
        'CIPRES',
        'FRAY MARCOS RAMIREZ DE PRADO',
        'VALENTIN GOMEZ FARIAS',
        'REY TIZOC',
        'PANOLANDA',
        'TAYACATA',
        'LUIS GUTIERREZ CORREA',
        'JUAN DE LA BARRERA',
        'ANTONIO DE SAAVEDRA 16VO. ALCALDE MAYOR',
        'JUAN ALVAREZ',
        'JUAREZ',
        'CAMPECHE',
        'MANUEL VILLASENOR',
        'URANO',
        'NUEZ',
        'CERRO DE VILLACHUATO',
        'MARIANO MICHELENA',
        'LICENCIADO JESUS RAMIREZ MENDOZA',
        'GENERAL GORDIANO GUZMAN',
        'TIERRA',
        'ERENDIRA',
        'REY TEZOZOMOC',
        'MANANTIALES DE MORELIA',
        'LA JOYA / JOSE TRINIDAD GUIDO',
        'ANTONIO ANCONA ALBERTO',
        'CURTIDORES DE TEREMENDO',
        'DEL VIVERO',
        'RIO CUPATITZIO',
        'CAPITAN CARLOS PANINI',
        'SOLIDARIDAD',
        'FRAY. SEBASTIAN DE APARICIO',
        'NUEVA TEPEYAC',
        'RIO CUPATITZIO',
        'MORELOS NORTE',
        'JUANA BARRAGAN',
        'CUAUTLA',
        'AGRICULTURA',
        'OLIVARES DE TZINTZUNTZAN',
        'ANTIGUO CAMINO A LA HUERTA',
        'FUENTES DE MORELIA',
        'NUEVO LEON',
        'TULIPAN',
        'MORELOS NORTE',
        'JOSE MARIA LINO PATINO',
        'ORIENTE 6',
        'EJE NORTE SUR',
        'PERIFERICO INDEPENDENCIA',
        '19 DE OCTUBRE',
        'MIRADOR MORELIA',
        'FLAMINGO',
        'GABINO LEON',
        'TORREON NUEVO',
        'CERRO DE VILLACHUATO',
        'TEPEYAC',
        'TENIENTE CORONEL FELIPE PARAMO',
        'HEROES DE NOCUPETARO',
        'PERIFERICO REPUBLICA',
        'ACUEDUCTO',
        'PERIFERICO PASEO DE LA REPUBLICA',
        'LA HUERTA',
        'HEROE DE LA REFORMA',
        'CALLE PASEO DE LA REPUBLICA',
        'LUIS MORA TOVAR',
        'OCTAVA',
        'VIRREY ANTONIO DE BUCARELI',
        'ORIENTE-PONIENTE',
        'HOMERO',
        'ALFILERILLO',
        'ANASTASIO NAJERA',
        'FINLANDIA',
        'VALLE DE GUAYANGUAREO',
        'GABRIEL MARIN Y ACOSTA',
        'MAESTRA MARIA DOLORES CALDERON',
        'HERNAN CORTES',
        'PERIFERICO REPUBLICA',
        'RINCON DEL ORO',
        'ENCUENTRO DE MARAVATIO',
        'GENERAL MANUEL DE LA PENA Y PENA',
        'CECILIO GARCIA',
        'JOAQUIN GARCIA GRANADOS',
        'GENERAL JOSE GREGORIO PATINO',
        'CUMANCHEN',
        'DEL TRANSPORTE',
        'PLACIDO VEGA',
        'MELCHOR OCAMPO MANZO',
        'MIRTO',
        'JOSE JUAN TABLADA',
        'LICENCIADO ENRIQUE RAMIREZ MIGUEL',
        'CALZADA LA HUERTA',
        'PERIFERICO NUEVA ESPANA',
        'MORELOS',
        'DALIA',
        'BATALLON DE MATAMOROS',
        'PERIFERICO NUEVA ESPANA',
        'BATALLA DE CHURUBUSCO',
        'PANOLANDA',
        'LA HUERTA',
        'REFORMA',
        'QUINTA',
        'PASEO DEL TABACHIN',
        'FRESA',
        'OCAMPO',
        'TANZANIA',
        'RIO MAYO',
        'AVENIDA AMERICAS',
        'PERIFERICO NUEVA ESPANA',
        'ORIENTE 4',
        'BAMBU',
        'VICENTE BARROSO DE LA ESCAYOLA',
        'JUAN SEBASTIAN BACH',
        'LOMA HODURENA',
        'SIN NOMBRE',
        'PERIFERICO PASEO DE LA REPUBLICA',
        'FRAY ANTONIO DE SAN MIGUEL IGLESIAS',
        'GALAXIAS',
        'FRANCISCO I. MADERO ORIENTE',
        'OBISPO MISIONERO',
        'JUAN BAUTISTA MARQUEZ',
        'PERIBAN',
        'VIRREY DE MENDOZA',
        'EPITACIO HUERTA',
        'SITIO DE CUAUTLA',


];
    
$numerosExt = [
        '1',
        'SN',
        'SN',
        '308',
        'SN',
        '11',
        '1896',
        '376',
        '274',
        '90',
        '422',
        '563',
        '3233',
        '536',
        '156',
        '189',
        '199',
        '237',
        '2021',
        '178',
        '65',
        '222',
        '11',
        '40',
        '162',
        '42',
        '330',
        '5714',
        '1939',
        '408',
        '31',
        '44',
        '53',
        '431',
        '4780',
        '3900',
        '152',
        '60 A',
        '899',
        '22',
        '133',
        '3846',
        '3001',
        '26',
        '386',
        '839',
        '126',
        '197',
        '448',
        '219',
        '207',
        '4340',
        '68',
        '46',
        '1483 A',
        '188',
        '935',
        'SN',
        '26 A',
        '625',
        '431',
        'SN',
        'SN',
        '56',
        '1290 A',
        '843',
        '180',
        '984',
        '220',
        '60',
        '121 A',
        '109',
        '42',
        '61',
        '189A',
        '1475',
        '572',
        '13',
        '248',
        '114',
        '176',
        '22',
        '73',
        '12',
        '852B',
        '936',
        '165 B',
        '400 A',
        '32',
        '36',
        '259',
        '63',
        '548',
        '103',
        '415',
        '148',
        'SN',
        '273',
        '111',
        '281',
        '946',
        '97',
        '897',
        '387',
        '1833',
        '13 A',
        '1057',
        '444',
        '344',
        '399',
        '3877 5',
        '530',
        '50',
        '545',
        '1046',
        '613',
        '337 A',
        '392',
        '18',
        '6155',
        '100',
        'SN',
        '50',
        '2520',
        'SN',
        '65 A',
        '62',
        '62',
        '240',
        '590',
        '150',
        'SN',
        '1851',
        '1377',
        '3364',
        '2400',
        '4005',
        '25',
        '2424',
        'KM17 216',
        '143',
        '1151',
        '431',
        '586',
        '49',
        'SN',
        '438',
        '47',
        '17',
        '196',
        '93',
        '7673',
        '318',
        '36',
        '475A',
        '187',
        '164',
        '1915',
        '175',
        '208',
        '237',
        'SN',
        '1340',
        '318',
        '1000',
        '3000',
        '5030',
        '1',
        '491',
        '472',
        '200',
        '29',
        '124',
        'KM 3.150',
        '51',
        '340',
        '868',
        '206',
        '18',
        '69',
        '755',
        '489',
        '421',
        '1600',
        '150',
        '155',
        '187',
        '98',
        'SN',
        '3843',
        '1503A',
        '378',
        '1920',
        '32',
        'SN',
        '553',
        '158',
        'SN',
        'SN'        

];
?>